// @vitest-environment edge-runtime
//
// Demo-fixture generator: runs the REAL backend (schema, seed, queries) in
// memory via convex-test and dumps every query result the screens read into
// src/lib/demo/fixtures.json. Used only by the screenshot harness — gated
// behind GEN_FIXTURES=1 so `npm test` stays side-effect free.
import { describe, expect, it } from "vitest";
import { convexTest } from "convex-test";
import { getFunctionName } from "convex/server";
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import schema from "../convex/schema";
import { api, internal } from "../convex/_generated/api";

const modules = import.meta.glob("../convex/**/!(*.*.*)*.*s");

function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value as Record<string, unknown>)
        .sort()
        .map((k) => [k, sortDeep((value as Record<string, unknown>)[k])]),
    );
  }
  return value;
}

export function fixtureKey(name: string, args: unknown): string {
  const clean = JSON.parse(JSON.stringify(args ?? {}));
  return `${name}|${JSON.stringify(sortDeep(clean))}`;
}

describe.runIf(process.env.GEN_FIXTURES === "1")("generate demo fixtures", () => {
  it("seeds in-memory and captures every screen query", async () => {
    const t = convexTest(schema, modules);
    const seeded = await t.mutation(internal.seed.run, {});
    expect(seeded.batteries).toBeGreaterThan(200);

    const fixtures: Record<string, unknown> = {};
    const capture = async (
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      ref: any,
      args: Record<string, unknown>,
    ) => {
      const result = await t.query(ref, args);
      fixtures[fixtureKey(getFunctionName(ref), args)] = result;
      return result;
    };

    for (const surface of ["admin", "oem", "partners", "field"] as const) {
      await capture(api.orgs.whoami, { surface });
    }

    // control tower
    await capture(api.batteries.registrySummary, {});
    await capture(api.trail.movements, { limit: 8 });
    await capture(api.trail.movements, { scope: "all", limit: 300 });
    const registry = (await capture(api.batteries.registry, {})) as {
      _id: string;
      stage: string;
      publicToken: string;
    }[];
    await capture(api.trail.trailForStaff, { batteryId: registry[0]!._id });
    await capture(api.containers.containerRegister, {});
    await capture(api.points.listPointsForStaff, {});
    await capture(api.permits.reviewQueue, {});
    await capture(api.anchors.list, {});
    await capture(api.labels.batches, {});

    // producer
    await capture(api.batteries.producerSummary, {});
    await capture(api.trail.myMovements, { limit: 8 });
    await capture(api.batteries.myBatteries, {});
    await capture(api.containers.myContainers, {});
    await capture(api.collections.myCollections, {});
    const reports = (await capture(api.reports.myReports, {})) as {
      reportId: string;
    }[];
    if (reports[0]) {
      await capture(api.reports.certificate, { reportId: reports[0].reportId });
      await capture(api.reports.verify, { reportId: reports[0].reportId });
    }

    // partner
    await capture(api.batteries.offtakeSummary, {});
    await capture(api.interests.myInterests, {});
    await capture(api.batteries.availableForOfftake, {});
    await capture(api.permits.myPermitState, {});
    await capture(api.permits.myPermits, {});

    // public + field
    await capture(api.points.listPublicPoints, {});
    const journeyed =
      registry.find((b) => b.stage === "second_life") ?? registry[0]!;
    await capture(api.trail.publicTrail, { token: journeyed.publicToken });
    await capture(api.collections.todayStops, {});
    await capture(api.trail.scanLookup, { tag: "RVL-00001" });

    const outDir = path.resolve(__dirname, "../src/lib/demo");
    mkdirSync(outDir, { recursive: true });
    writeFileSync(
      path.join(outDir, "fixtures.json"),
      JSON.stringify(
        { note: "Generated by tests/gen-fixtures.test.ts from the real seed via convex-test.", fixtures },
        null,
        1,
      ),
    );
    expect(Object.keys(fixtures).length).toBeGreaterThan(25);
  });
});

describe("fixtureKey", () => {
  it("is stable across key order and drops undefined", () => {
    expect(fixtureKey("a:b", { x: 1, y: "z" })).toBe(
      fixtureKey("a:b", { y: "z", x: 1 }),
    );
    expect(fixtureKey("a:b", { x: 1, y: undefined })).toBe(
      fixtureKey("a:b", { x: 1 }),
    );
  });
});
